title: JuLee Household
background: no-repeat center / cover url("/local/images/backgrounds/background.png") fixed 
#background: "right/auto linear-gradient(23deg, rgba(211,211,211,1) 0%, rgba(223,223,223,1) 34%, rgba(255,255,255,1) 100%)"
### Custom Header ###
custom_header:
  compact_mode: true 
  shadow: true 
  hide_help: true 
  hide_config: true 
  header_css: 'background: rgba(0,0,0,0.3);'
  tab_indicator_color: '#5294E2'
  active_tab_color: '#5294E2'

### Load resources required by Lovelace ###
resources: !include lovelace/resources.yaml

button_card_templates:
  !include lovelace/button_card_templates/button_card_templates.yaml

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

### Split the various tabs into seperate files ###
views:
  - !include lovelace/home.yaml
  - !include lovelace/summary.yaml
  - !include lovelace/cast.yaml
  - !include lovelace/system.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/dashboard.yaml
  - !include lovelace/automations-scripts.yaml
