homeassistant:
  customize:
    sensor.device_lee_pc:
      icon: mdi:desktop-tower-monitor
      templates:
        icon_color: "if (state === 'Online') return 'rgb(0,180,0)';
        else if (state === 'Unknown') return 'rgb(127,127,127)';
        else if (state === 'Offline') return 'rgb(210,0,0)';"
        
sensor:
  - platform: template
    sensors:
      device_lee_pc:
        friendly_name: Lee PC
        entity_id: "device_tracker.lee_pc"
        value_template: >-
          {% if is_state('device_tracker.lee_pc', 'home') %}
            Online
          {% elif is_state('device_tracker.lee_pc', 'not_home') %}
            Offline
          {% else %}
            Unknown
          {% endif %}

input_select:
  device_lee_pc_status:
    name: 'My PC' 
    options:
      - Online
      - Offline
      - Unknown
    initial: Online

automation:
  - alias: '[Tracking] Device Online'
    trigger:
      - platform: state
        entity_id: sensor.device_lee_pc
        to: 'Online'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.device_lee_pc_status
          option: Online 

  - alias: '[Tracking] Device Offline'
    trigger:
      - platform: state
        entity_id: sensor.device_lee_pc
        to: 'Offline'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.device_lee_pc_status
          option: Offline

  - alias: '[Tracking] Device Unknown'
    trigger:
      - platform: state
        entity_id: sensor.device_lee_pc
        to: 'Unknown'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.device_lee_pc_status
          option: Unknown