plex:
  host: !secret plex_host_ip
  port: !secret plex_host_port
  token: !secret plex_token
  server: 'Home Media'
  media_player:
    use_episode_art: true
    show_all_controls: true

sensor:
  - platform: plex_recently_added
    name: Recently Added Movies 
    token: !secret plex_token
    host: !secret plex_host_ip
    port: !secret plex_host_port
    download_images: true
    max: 3
    section_types:
    - movie

  - platform: plex_recently_added
    name: Recently Added TV  
    token: !secret plex_token
    host: !secret plex_host_ip
    port: !secret plex_host_port
    download_images: true
    max: 3
    section_types:
    - show